title: jekyll-bulma-feather
navbar:
  title: JBF
  logo: /assets/jekyll-bulma-feather.svg
  start:
    - title: Home
      url: /
      icon: home
    - title: License
      url: /COPYING
      icon: file-text
  end:
    - title: GitHub
      url: https://github.com/YellowApple/jekyll-bulma-feather
      icon: github
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
